### ISSUE TITLE
Improve styling to my liking

### ISSUE THREAD

**Issue by josharnow** [josharnow/My-Personal-Website#18]
- https://primereact.org
- https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/

### Tasks
- [ ] Theme PrimeReact components (https://primereact.org/theming/)
- [ ] https://www.youtube.com/watch?v=RPa3_AD1_Vs&t=394s
  - [ ] [MacBook scroll effect](https://ui.aceternity.com/components/macbook-scroll)

**Comment by josharnow** [comment]
Adding [ripples](https://primevue.org/ripple/) when clicking buttons provides a nice effect
