### ISSUE TITLE
Create education & work timelines

### ISSUE THREAD

**Issue by josharnow** [josharnow/My-Personal-Website#20]
**Problem**
Displaying education & work history in a clean way

**Solution**
Create a timeline

**Necessary Tools**
- [Stepper component](https://primevue.org/stepper/)
OR
- [Timeline component](https://primevue.org/timeline/)

**Implementation**
- [ ] Create education timeline
- [ ] Create work timeline

## Components
- [Card Spotlight](https://ui.aceternity.com/components/card-spotlight)
- [Expandable Cards](https://ui.aceternity.com/components/expandable-card)
- [Background Gradient](https://ui.aceternity.com/components/background-gradient)

## TODO
- [x] Transition animations for box that appears behind selected year (Timeline component)
- [ ] Add logos
- [ ] Content
- [ ] Mobile responsiveness
  - [ ] On mobile, add left/right clickers to move between years since it'll be too difficult to actually click on the timeline

**Comment by josharnow** [comment]
I'm leaning towards the timeline component so that the page can still be scrolled and I can use [animation effects](https://primevue.org/animateonscroll/).

If I go with that option, I should also add a [ScrollTop](https://primevue.org/scrolltop/) component so that users can easily navigate back to the top of the page after reaching the bottom.
